In [2]:
import cv2
import numpy as np
import os

In [39]:
get_hog('dataset/Indian-monuments/hog/lotus_temple/100.jfif','100.jfif','Dataset/Indian-monuments/hog/lotus_temple/')

error: OpenCV(4.6.0) D:/a/opencv-python/opencv-python/opencv/modules/imgproc/src/filter.simd.hpp:3143: error: (-213:The function/feature is not implemented) Unsupported combination of buffer format (=6), and destination format (=5) in function 'cv::opt_AVX2::getLinearColumnFilter'


In [55]:
img = cv2.imread('Dataset/Indian-monuments/images/train/lotus_temple/100.jfif')
print(img)
cv2.imwrite("test_img.jfif",img)

[[[184 117  90]
  [184 117  90]
  [184 117  90]
  ...
  [184 124  95]
  [183 125  96]
  [189 131 102]]

 [[182 115  88]
  [182 115  88]
  [182 115  88]
  ...
  [178 118  89]
  [174 114  85]
  [178 120  91]]

 [[179 112  85]
  [179 112  85]
  [179 112  85]
  ...
  [173 113  84]
  [169 109  80]
  [175 115  86]]

 ...

 [[ 84 158 154]
  [ 79 153 149]
  [ 79 146 141]
  ...
  [ 18  15  17]
  [ 22  19  21]
  [ 17  14  16]]

 [[110 186 185]
  [110 185 183]
  [112 183 180]
  ...
  [ 18  15  17]
  [ 22  19  21]
  [ 15  12  14]]

 [[ 92 174 175]
  [ 65 145 144]
  [ 66 142 141]
  ...
  [ 18  15  17]
  [ 18  15  17]
  [ 18  15  17]]]


error: OpenCV(4.6.0) D:\a\opencv-python\opencv-python\opencv\modules\imgcodecs\src\loadsave.cpp:730: error: (-2:Unspecified error) could not find a writer for the specified extension in function 'cv::imwrite_'


In [58]:
def get_hog(input_img,image_name, output_dir):
    img = cv2.imread(input_img)
    img= np.float32(img) / 255.0

    gx = cv2.Sobel(img, cv2.CV_32F, 1, 0, ksize=1)
    gy = cv2.Sobel(img, cv2.CV_32F, 0, 1, ksize=1)

    mag, angle = cv2.cartToPolar(gx, gy, angleInDegrees=True)
    mag = cv2.resize(mag,(img.shape[1]//2, img.shape[0]//2))
    img_output = mag * 255.0
    img_output = img_output.astype('uint8')
    image_name = image_name[:image_name.index('.')] + '.jpg'
    cv2.imwrite(output_dir+image_name,img_output)

In [64]:
base_dir = 'Dataset/Indian-monuments/images/test'
for i in os.listdir(base_dir):
    print(i)
    os.mkdir('Dataset/Indian-monuments/hog_test/'+i)
    d = os.path.join(base_dir, i)
    os.path.isdir(d)
    for images in os.listdir(d):
        img_path = os.path.join(d, images)
        print(images)
        print(img_path)
        get_hog(img_path,images, "Dataset/Indian-monuments/hog_test/"+i+"/")

Ajanta Caves
1.jpg
Dataset/Indian-monuments/images/test\Ajanta Caves\1.jpg
10.jpg
Dataset/Indian-monuments/images/test\Ajanta Caves\10.jpg
11.jpg
Dataset/Indian-monuments/images/test\Ajanta Caves\11.jpg
12.jpg
Dataset/Indian-monuments/images/test\Ajanta Caves\12.jpg
13.jpg
Dataset/Indian-monuments/images/test\Ajanta Caves\13.jpg
14.jpg
Dataset/Indian-monuments/images/test\Ajanta Caves\14.jpg
15.jpg
Dataset/Indian-monuments/images/test\Ajanta Caves\15.jpg
16.jpg
Dataset/Indian-monuments/images/test\Ajanta Caves\16.jpg
17.jpg
Dataset/Indian-monuments/images/test\Ajanta Caves\17.jpg
18.jpg
Dataset/Indian-monuments/images/test\Ajanta Caves\18.jpg
19.jpg
Dataset/Indian-monuments/images/test\Ajanta Caves\19.jpg
2.jpg
Dataset/Indian-monuments/images/test\Ajanta Caves\2.jpg
20.jpg
Dataset/Indian-monuments/images/test\Ajanta Caves\20.jpg
21.jpg
Dataset/Indian-monuments/images/test\Ajanta Caves\21.jpg
22.jpg
Dataset/Indian-monuments/images/test\Ajanta Caves\22.jpg
23.jpg
Dataset/Indian-monuments

24.jpg
Dataset/Indian-monuments/images/test\basilica_of_bom_jesus\24.jpg
25.jpg
Dataset/Indian-monuments/images/test\basilica_of_bom_jesus\25.jpg
26.jpg
Dataset/Indian-monuments/images/test\basilica_of_bom_jesus\26.jpg
27.jpg
Dataset/Indian-monuments/images/test\basilica_of_bom_jesus\27.jpg
28.jpg
Dataset/Indian-monuments/images/test\basilica_of_bom_jesus\28.jpg
29.jpg
Dataset/Indian-monuments/images/test\basilica_of_bom_jesus\29.jpg
3.jpg
Dataset/Indian-monuments/images/test\basilica_of_bom_jesus\3.jpg
30.jpg
Dataset/Indian-monuments/images/test\basilica_of_bom_jesus\30.jpg
4.jpg
Dataset/Indian-monuments/images/test\basilica_of_bom_jesus\4.jpg
5.jpg
Dataset/Indian-monuments/images/test\basilica_of_bom_jesus\5.jpg
6.jpg
Dataset/Indian-monuments/images/test\basilica_of_bom_jesus\6.jpg
7.jpg
Dataset/Indian-monuments/images/test\basilica_of_bom_jesus\7.jpg
8.jpg
Dataset/Indian-monuments/images/test\basilica_of_bom_jesus\8.jpg
9.jpg
Dataset/Indian-monuments/images/test\basilica_of_bom_jesu

26.jpg
Dataset/Indian-monuments/images/test\Ellora Caves\26.jpg
27.jpg
Dataset/Indian-monuments/images/test\Ellora Caves\27.jpg
28.jpg
Dataset/Indian-monuments/images/test\Ellora Caves\28.jpg
29.jpg
Dataset/Indian-monuments/images/test\Ellora Caves\29.jpg
3.jpg
Dataset/Indian-monuments/images/test\Ellora Caves\3.jpg
30.jpg
Dataset/Indian-monuments/images/test\Ellora Caves\30.jpg
31.jpg
Dataset/Indian-monuments/images/test\Ellora Caves\31.jpg
32.jpg
Dataset/Indian-monuments/images/test\Ellora Caves\32.jpg
33.jpg
Dataset/Indian-monuments/images/test\Ellora Caves\33.jpg
34.jpg
Dataset/Indian-monuments/images/test\Ellora Caves\34.jpg
4.jpg
Dataset/Indian-monuments/images/test\Ellora Caves\4.jpg
5.jpg
Dataset/Indian-monuments/images/test\Ellora Caves\5.jpg
6.jpg
Dataset/Indian-monuments/images/test\Ellora Caves\6.jpg
7.jpg
Dataset/Indian-monuments/images/test\Ellora Caves\7.jpg
8.jpg
Dataset/Indian-monuments/images/test\Ellora Caves\8.jpg
9.jpg
Dataset/Indian-monuments/images/test\Ellora Ca

images-162.jpeg
Dataset/Indian-monuments/images/test\Hawa mahal\images-162.jpeg
images-163.jpeg
Dataset/Indian-monuments/images/test\Hawa mahal\images-163.jpeg
images-164.jpeg
Dataset/Indian-monuments/images/test\Hawa mahal\images-164.jpeg
images-165.jpeg
Dataset/Indian-monuments/images/test\Hawa mahal\images-165.jpeg
images-166.jpeg
Dataset/Indian-monuments/images/test\Hawa mahal\images-166.jpeg
images-167.jpeg
Dataset/Indian-monuments/images/test\Hawa mahal\images-167.jpeg
images-168.jpeg
Dataset/Indian-monuments/images/test\Hawa mahal\images-168.jpeg
images-169.jpeg
Dataset/Indian-monuments/images/test\Hawa mahal\images-169.jpeg
images-170.jpeg
Dataset/Indian-monuments/images/test\Hawa mahal\images-170.jpeg
images-171.jpeg
Dataset/Indian-monuments/images/test\Hawa mahal\images-171.jpeg
images-172.jpeg
Dataset/Indian-monuments/images/test\Hawa mahal\images-172.jpeg
images-173.jpeg
Dataset/Indian-monuments/images/test\Hawa mahal\images-173.jpeg
images-174.jpeg
Dataset/Indian-monuments

img11.jpg
Dataset/Indian-monuments/images/test\iron_pillar\img11.jpg
img110.jpg
Dataset/Indian-monuments/images/test\iron_pillar\img110.jpg
img111.jpg
Dataset/Indian-monuments/images/test\iron_pillar\img111.jpg
img112.jpg
Dataset/Indian-monuments/images/test\iron_pillar\img112.jpg
img13.jpg
Dataset/Indian-monuments/images/test\iron_pillar\img13.jpg
img14.jpg
Dataset/Indian-monuments/images/test\iron_pillar\img14.jpg
img15.jpg
Dataset/Indian-monuments/images/test\iron_pillar\img15.jpg
img16.jpg
Dataset/Indian-monuments/images/test\iron_pillar\img16.jpg
img17.jpg
Dataset/Indian-monuments/images/test\iron_pillar\img17.jpg
img18.jpg
Dataset/Indian-monuments/images/test\iron_pillar\img18.jpg
img19.jpg
Dataset/Indian-monuments/images/test\iron_pillar\img19.jpg
img20.jpg
Dataset/Indian-monuments/images/test\iron_pillar\img20.jpg
img21.jpg
Dataset/Indian-monuments/images/test\iron_pillar\img21.jpg
img22.jpg
Dataset/Indian-monuments/images/test\iron_pillar\img22.jpg
img23.jpg
Dataset/Indian-mon

img379.jpg
Dataset/Indian-monuments/images/test\jamali_kamali_tomb\img379.jpg
img380.jpg
Dataset/Indian-monuments/images/test\jamali_kamali_tomb\img380.jpg
img381.jpg
Dataset/Indian-monuments/images/test\jamali_kamali_tomb\img381.jpg
img385.jpg
Dataset/Indian-monuments/images/test\jamali_kamali_tomb\img385.jpg
img386.jpg
Dataset/Indian-monuments/images/test\jamali_kamali_tomb\img386.jpg
img388.jpg
Dataset/Indian-monuments/images/test\jamali_kamali_tomb\img388.jpg
img390.jpg
Dataset/Indian-monuments/images/test\jamali_kamali_tomb\img390.jpg
img393.jpg
Dataset/Indian-monuments/images/test\jamali_kamali_tomb\img393.jpg
img394.jpg
Dataset/Indian-monuments/images/test\jamali_kamali_tomb\img394.jpg
img396.jpg
Dataset/Indian-monuments/images/test\jamali_kamali_tomb\img396.jpg
img397.jpg
Dataset/Indian-monuments/images/test\jamali_kamali_tomb\img397.jpg
img400.jpg
Dataset/Indian-monuments/images/test\jamali_kamali_tomb\img400.jpg
Khajuraho
1.jpg
Dataset/Indian-monuments/images/test\Khajuraho\1

img20.jpg
Dataset/Indian-monuments/images/test\qutub_minar\img20.jpg
img21.jpg
Dataset/Indian-monuments/images/test\qutub_minar\img21.jpg
img22.jpg
Dataset/Indian-monuments/images/test\qutub_minar\img22.jpg
img23.jpg
Dataset/Indian-monuments/images/test\qutub_minar\img23.jpg
img24.jpg
Dataset/Indian-monuments/images/test\qutub_minar\img24.jpg
img25.jpg
Dataset/Indian-monuments/images/test\qutub_minar\img25.jpg
img26.jpg
Dataset/Indian-monuments/images/test\qutub_minar\img26.jpg
img27.jpg
Dataset/Indian-monuments/images/test\qutub_minar\img27.jpg
img28.jpg
Dataset/Indian-monuments/images/test\qutub_minar\img28.jpg
img29.jpg
Dataset/Indian-monuments/images/test\qutub_minar\img29.jpg
img3.jpg
Dataset/Indian-monuments/images/test\qutub_minar\img3.jpg
img30.jpg
Dataset/Indian-monuments/images/test\qutub_minar\img30.jpg
img31.jpg
Dataset/Indian-monuments/images/test\qutub_minar\img31.jpg
img32.jpg
Dataset/Indian-monuments/images/test\qutub_minar\img32.jpg
img33.jpg
Dataset/Indian-monuments/i

gettyimages-1143915849-612x612.jpeg
Dataset/Indian-monuments/images/test\tajmahal\gettyimages-1143915849-612x612.jpeg
gettyimages-1155258851-612x612.jpeg
Dataset/Indian-monuments/images/test\tajmahal\gettyimages-1155258851-612x612.jpeg
gettyimages-1155675166-612x612.jpeg
Dataset/Indian-monuments/images/test\tajmahal\gettyimages-1155675166-612x612.jpeg
gettyimages-157771864-612x612.jpeg
Dataset/Indian-monuments/images/test\tajmahal\gettyimages-157771864-612x612.jpeg
gettyimages-470592191-612x612.jpeg
Dataset/Indian-monuments/images/test\tajmahal\gettyimages-470592191-612x612.jpeg
gettyimages-479761744-612x612.jpeg
Dataset/Indian-monuments/images/test\tajmahal\gettyimages-479761744-612x612.jpeg
gettyimages-486118555-612x612.jpeg
Dataset/Indian-monuments/images/test\tajmahal\gettyimages-486118555-612x612.jpeg
gettyimages-498507139-612x612.jpeg
Dataset/Indian-monuments/images/test\tajmahal\gettyimages-498507139-612x612.jpeg
gettyimages-509658458-612x612.jpeg
Dataset/Indian-monuments/images

193.jpg
Dataset/Indian-monuments/images/test\victoria memorial\193.jpg
194.jpg
Dataset/Indian-monuments/images/test\victoria memorial\194.jpg
195.jpg
Dataset/Indian-monuments/images/test\victoria memorial\195.jpg
196.jpg
Dataset/Indian-monuments/images/test\victoria memorial\196.jpg
197.jpg
Dataset/Indian-monuments/images/test\victoria memorial\197.jpg
198.jpg
Dataset/Indian-monuments/images/test\victoria memorial\198.jpg
199.jpg
Dataset/Indian-monuments/images/test\victoria memorial\199.jpg
200.jpg
Dataset/Indian-monuments/images/test\victoria memorial\200.jpg


In [3]:
def show_img(img):
    cv2.imshow("Image", img)
    cv2.waitKey(0)
    cv2.destroyAllWindows()

In [16]:
def get_hog(input_img, output_dir):
    img = cv2.imread(input_img)
    img= np.float32(img) / 255.0

    gx = cv2.Sobel(img, cv2.CV_32F, 1, 0, ksize=1)
    gy = cv2.Sobel(img, cv2.CV_32F, 0, 1, ksize=1)

    mag, angle = cv2.cartToPolar(gx, gy, angleInDegrees=True)
    mag = cv2.resize(mag,(img.shape[1]//2, img.shape[0]//2))
    img_output = mag * 255.0
    img_output = img_output.astype('uint8')
    cv2.imwrite(output_dir+input_img,img_output)

In [4]:
img = cv2.imread('tajmahal.jpg')
img= np.float32(img) / 255.0
 
gx = cv2.Sobel(img, cv2.CV_32F, 1, 0, ksize=1)
gy = cv2.Sobel(img, cv2.CV_32F, 0, 1, ksize=1)

mag, angle = cv2.cartToPolar(gx, gy, angleInDegrees=True)

In [5]:
mag = cv2.resize(mag,(img.shape[1]//2, img.shape[0]//2))
show_img(mag)

In [8]:
img_output = mag * 255.0

In [11]:
img_output = img_output.astype('uint8')

In [15]:
cv2.imwrite("image_output.jpg",img_output)

True

## K Means

In [50]:
img = cv2.imread('tajmahal.jpg')

In [51]:
image = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
# reshape the image to a 2D array of pixels and 3 color values (RGB)
pixel_values = image.reshape((-1, 3))
# convert to float
pixel_values = np.float32(pixel_values)

In [52]:
criteria = (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER, 100, 0.2)

In [79]:
k = 3
_, labels, (centers) = cv2.kmeans(pixel_values, k, None, criteria, 10, cv2.KMEANS_RANDOM_CENTERS)

In [80]:
# convert back to 8 bit values
centers = np.uint8(centers)

# flatten the labels array
labels = labels.flatten()

In [81]:
segmented_image = centers[labels.flatten()]
print(segmented_image)

[[ 82 135 193]
 [ 82 135 193]
 [ 82 135 193]
 ...
 [220 212 204]
 [220 212 204]
 [220 212 204]]


In [82]:
# reshape back to the original image dimension
segmented_image = segmented_image.reshape(image.shape)
# show the image
segmented_image = segmented_image.astype('uint8')
show_img(segmented_image)

In [86]:
# disable only the cluster number 2 (turn the pixel into black)
masked_image = np.copy(segmented_image)
# convert to the shape of a vector of pixel values
masked_image = masked_image.reshape((-1, 3))
# color (i.e cluster) to disable
masked_image[labels == 0] = [0, 0, 0]
masked_image[labels == 1] = [0, 0, 0]
# masked_image[labels == 3] = [0, 0, 0]
# convert back to original shape
masked_image = masked_image.reshape(image.shape)
# show the image
cv2.imwrite("tajmahal_kmeans.jpg", masked_image)
masked_image = cv2.resize(masked_image, (masked_image.shape[1]//2, masked_image.shape[0]//2))
show_img(masked_image)

## SIFT

In [1]:
import cv2 
import matplotlib.pyplot as plt
%matplotlib inline

# read images
img1 = cv2.imread('charminar_2.jpeg')  
img2 = cv2.imread('charminar_1.jpeg') 

img1 = cv2.cvtColor(img1, cv2.COLOR_BGR2GRAY)
img2 = cv2.cvtColor(img2, cv2.COLOR_BGR2GRAY)

#sift
sift = cv2.SIFT_create()

keypoints_1, descriptors_1 = sift.detectAndCompute(img1,None)
keypoints_2, descriptors_2 = sift.detectAndCompute(img2,None)

#feature matching
bf = cv2.BFMatcher(cv2.NORM_L1, crossCheck=True)

matches = bf.match(descriptors_1,descriptors_2)
matches = sorted(matches, key = lambda x:x.distance)

img3 = cv2.drawMatches(img1, keypoints_1, img2, keypoints_2, matches[:50], img2, flags=2)
# show_img(img3)
cv2.imwrite("image.jpg",img3)

True